<div id="<?= PREFIX ?>-<?= LOADING_CONTENTS['id'] ?>" class="<?= PREFIX ?>-<?= LOADING_CONTENTS['id'] ?>">

    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgb(255, 255, 255); display: block; shape-rendering: auto;" width="<?= LOADING_CONTENTS['iconWidth'] ?>" height="<?= LOADING_CONTENTS['iconHeight'] ?>" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
        <circle cx="50" cy="50" fill="none" stroke="<?= LOADING_CONTENTS['iconColor'] ?>" stroke-width="10" r="35" stroke-dasharray="164.93361431346415 56.97787143782138">
        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;360 50 50" keyTimes="0;1"></animateTransform>
        </circle>
        <!-- [ldio] generated by https://loading.io/ -->
    </svg>

</div>




